### ISSUE TITLE
`options` destructuring breaks setting default values

### ISSUE THREAD

**Issue by ianschmitz** [wobsoriano/authey#10]
I think there was a mix up here with what looks like attempting to set default values for some of the provided options to both `createAuthMiddleware` and `getSession`.

In the following code: https://github.com/wobsoriano/authey/blob/a49cccd469b00a0aaca9ac74dd6199a51173c417/src/index.ts#L65-L72

You can see that both `options.secret` and `options.trustHost` are set _after_ being destructured to `authOptions`. 

Perhaps something like the following was intended:

```ts
  const {
    prefix = '/api/auth',
    conform = (_: Request) => (res: Response) => res,
    ...authOptions
  } = options

  authOptions.secret ??= process.env.AUTH_SECRET
  authOptions.trustHost ??= shouldTrustHost()
```

The same issue applies to `getSession`.

nit: i would argue that the previous form was also not the best as it was mutating the options passed in to the function, which consumers may not be expecting.

**Comment by wobsoriano** [comment]
Very good find, I missed that one! And also, you're correct that it's not the best practice to mutate options passed.

Published an update, thanks!
